java
import java.util.Random;
import java.util.Scanner;

public class MathQuiz {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        Random random = new Random();
        int num1, num2, operator, correctAnswer, userAnswer;
        String[] operators = {"+", "-", "*", "/"};
        String response;

        do {
            operator = random.nextInt(4);
            num1 = random.nextInt(10) + 1;
            num2 = random.nextInt(10) + 1;

            switch (operators[operator]) {
                case "+":
                    correctAnswer = num1 + num2;
                    System.out.printf("What is %d + %d? ", num1, num2);
                    break;
                case "-":
                    correctAnswer = num1 - num2;
                    System.out.printf("What is %d - %d? ", num1, num2);
                    break;
                case "*":
                    correctAnswer = num1 * num2;
                    System.out.printf("What is %d * %d? ", num1, num2);
                    break;
                default:
                    correctAnswer = num1 / num2;
                    System.out.printf("What is %d / %d? ", num1, num2);
                    break;
            }

            userAnswer = scanner.nextInt();

            if (userAnswer == correctAnswer) {
                int responseIndex = random.nextInt(4);
                switch (responseIndex) {
                    case 0:
                        response = "¡Muy bien!";
                        break;
                    case 1:
                        response = "¡Excelente!";
                        break;
                    case 2:
                        response = "¡Buen trabajo!";
                        break;
                    default:
                        response = "¡Sigue así!";
                        break;
                }
            } else {
                int responseIndex = random.nextInt(4);
                switch (responseIndex) {
                    case 0:
                        response = "No. Por favor intenta de nuevo.";
                        break;
                    case 1:
                        response = "Incorrecto. Intenta una vez más.";
                        break;
                    case 2:
                        response = "¡No te rindas!";
                        break;
                    default:
                        response = "Sigue intentando.";
                        break;
                }
            }

            System.out.println(response);
            System.out.println("Presiona 1 para continuar o cualquier otro número para salir.");
        } while (scanner.nextInt() == 1);
    }
}
